language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install firebase-tools -g
script:
  - npm install
  - ng build --prod
  - firebase deploy --only hosting --token "1//06OKKHdhNQDufCgYIARAAGAYSNwF-L9IrXZKAdIYjuNP_inNYExrzB00cN3J7YYyOFnnbDwFIuIMhYfnKUpKumpVVethOmp3ghPY"